/**
 * Private parent bridge for ADR-0008 management writes.
 *
 * The Go sidecar never receives a browser session or admin token. Instead, the
 * TypeScript front door admits the public request, signs one exact mutation,
 * and the sidecar returns that assertion over its loopback-only bridge. This
 * module re-verifies both layers before asking the legacy TypeScript handler
 * to execute the mutation. It deliberately knows no handler paths itself: the
 * management route registry remains the ownership authority.
 */
import { createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import type { ManagementPrincipal } from "./management-auth";
import { findGoOwnedManagementRoute, type HttpMethod } from "./management/route-registry";

export const GO_SIDECAR_WRITE_BRIDGE_PATH = "/__ocx_go_sidecar/write";
export const GO_SIDECAR_BRIDGE_HEADER = "x-ocx-go-sidecar-bridge";
export const GO_SIDECAR_WRITE_RELAY_NONCE_HEADER = "x-ocx-go-sidecar-relay-nonce";
export const GO_SIDECAR_WRITE_RELAY_PRINCIPAL_HEADER = "x-ocx-go-sidecar-relay-principal";
export const GO_SIDECAR_WRITE_RELAY_METHOD_HEADER = "x-ocx-go-sidecar-relay-method";
export const GO_SIDECAR_WRITE_RELAY_PATH_HEADER = "x-ocx-go-sidecar-relay-path";
export const GO_SIDECAR_WRITE_RELAY_EXPIRES_AT_HEADER = "x-ocx-go-sidecar-relay-expires-at";
export const GO_SIDECAR_WRITE_RELAY_PROOF_HEADER = "x-ocx-go-sidecar-relay-proof";

const RELAY_VERSION = "opencodex-go-write-relay-v1";
const RELAY_TTL_MS = 30_000;
const RELAY_REPLAY_LIMIT = 256;
const MAX_WRITE_BODY_BYTES = 2 * 1024 * 1024;
const BASE64URL_256 = /^[A-Za-z0-9_-]{43}$/;
const EXPIRY = /^[1-9]\d*$/;
const PATH = /^\/[^?#\r\n]*$/;
const HTTP_METHODS = new Set<HttpMethod>(["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"]);
const PRINCIPALS = new Set<ManagementPrincipal>([
  "admin-token",
  "gui-session",
  "gui-pair-capability",
  "local-read-capability",
  "local-provider-reload-capability",
  "system-restart-capability",
]);

export interface GoSidecarWriteRelayClaim {
  nonce: string;
  principal: ManagementPrincipal;
  method: HttpMethod;
  path: string;
  expiresAt: number;
  proof: string;
}

export interface GoSidecarWriteRelay {
  handle(request: Request, url: URL): Promise<Response>;
}

export interface GoSidecarWriteRelayOptions {
  /** Per-sidecar capability, distinct from the signed claim. */
  bridgeToken: string;
  /** Shared only with the supervised sidecar through its process environment. */
  relaySecret: string;
  /** Calls legacy TypeScript management dispatch with sidecar forwarding disabled. */
  dispatchLegacy(request: Request, url: URL, principal: ManagementPrincipal): Promise<Response | null>;
  now?: () => number;
}

export function createGoSidecarWriteRelayNonce(): string {
  return randomBytes(32).toString("base64url");
}

/** Signs the Go-compatible, body-bound relay claim. The supervisor uses this on the public hop. */
export function createGoSidecarWriteRelayProof(
  secret: string,
  claim: Omit<GoSidecarWriteRelayClaim, "proof">,
  body: Uint8Array,
): string | null {
  const payload = relayPayload(claim, body);
  if (!payload || !isRelaySecret(secret)) return null;
  return createHmac("sha256", secret).update(payload).digest("base64url");
}

/**
 * Mint the complete parent-to-sidecar header set for one already-admitted
 * public write. This is intentionally separate from bridge verification so
 * the supervisor cannot accidentally reuse a static header set across bodies.
 */
export function createGoSidecarWriteRelayHeaders(
  secret: string,
  principal: ManagementPrincipal | undefined,
  request: { method: string; pathname: string; body: Uint8Array },
  now: () => number = Date.now,
): Headers | null {
  if (!principal || !PRINCIPALS.has(principal) || !HTTP_METHODS.has(request.method as HttpMethod)) return null;
  const expiresAt = now() + RELAY_TTL_MS;
  if (!Number.isSafeInteger(expiresAt)) return null;
  const claim = {
    nonce: createGoSidecarWriteRelayNonce(),
    principal,
    method: request.method as HttpMethod,
    path: request.pathname,
    expiresAt,
  };
  const proof = createGoSidecarWriteRelayProof(secret, claim, request.body);
  if (!proof) return null;
  return new Headers({
    [GO_SIDECAR_WRITE_RELAY_NONCE_HEADER]: claim.nonce,
    [GO_SIDECAR_WRITE_RELAY_PRINCIPAL_HEADER]: claim.principal,
    [GO_SIDECAR_WRITE_RELAY_METHOD_HEADER]: claim.method,
    [GO_SIDECAR_WRITE_RELAY_PATH_HEADER]: claim.path,
    [GO_SIDECAR_WRITE_RELAY_EXPIRES_AT_HEADER]: String(claim.expiresAt),
    [GO_SIDECAR_WRITE_RELAY_PROOF_HEADER]: proof,
  });
}

export function createGoSidecarWriteRelay(options: GoSidecarWriteRelayOptions): GoSidecarWriteRelay | null {
  // The bridge capability is generated by the parent with randomUUID(), while
  // the relay secret is a 32-byte base64url HMAC key. Do not accidentally
  // require the two independent credentials to share an encoding.
  if (!isBridgeToken(options.bridgeToken) || !isRelaySecret(options.relaySecret)) return null;
  const now = options.now ?? Date.now;
  const consumed = new Map<string, number>();

  return {
    async handle(request, url): Promise<Response> {
      if (
        request.method !== "PUT"
        || url.pathname !== GO_SIDECAR_WRITE_BRIDGE_PATH
        || url.search !== ""
        || !equalSecret(request.headers.get(GO_SIDECAR_BRIDGE_HEADER), options.bridgeToken)
      ) return notFound();

      const claim = claimFromHeaders(request.headers);
      if (!claim) return notFound();
      const route = findGoOwnedManagementRoute(claim.method, claim.path);
      if (!route || !route.mutates || route.go.relay !== "signed") return notFound();

      let body: Uint8Array;
      try {
        body = await readBoundedBody(request, MAX_WRITE_BODY_BYTES);
      } catch {
        return new Response(JSON.stringify({ error: "request body too large" }), {
          status: 413,
          headers: { "content-type": "application/json" },
        });
      }

      const clock = now();
      if (
        !Number.isSafeInteger(clock)
        || claim.expiresAt <= clock
        || claim.expiresAt > clock + RELAY_TTL_MS
        || !verifyProof(options.relaySecret, claim, body)
      ) return notFound();

      pruneConsumed(consumed, clock);
      if (consumed.has(claim.nonce) || consumed.size >= RELAY_REPLAY_LIMIT) return notFound();
      // Spend before dispatch: a transport retry cannot execute a mutation twice.
      consumed.set(claim.nonce, claim.expiresAt);

      const headers = new Headers();
      const contentType = request.headers.get("content-type");
      const host = request.headers.get("host");
      if (contentType) headers.set("content-type", contentType);
      // The parent bridge reconstructs a Request and reuses normal management
      // validation. Preserve its own loopback Host so origin comparison sees
      // the same authority as the public request; never copy client cookies or
      // authorization credentials.
      if (host) headers.set("host", host);
      if (body.byteLength > 0) headers.set("content-length", String(body.byteLength));
      const legacyUrl = new URL(claim.path, url);
      // Copy into an ArrayBuffer-backed view: TypeScript's DOM declaration
      // rejects a possibly SharedArrayBuffer-backed Uint8Array as a Blob part.
      const legacyBody = body.byteLength > 0 ? new Blob([new Uint8Array(body)]) : undefined;
      const legacyRequest = new Request(legacyUrl, {
        method: claim.method,
        headers,
        body: legacyBody,
      });
      const response = await options.dispatchLegacy(legacyRequest, legacyUrl, claim.principal);
      return response ?? notFound();
    },
  };
}

function claimFromHeaders(headers: Headers): GoSidecarWriteRelayClaim | null {
  const nonce = headers.get(GO_SIDECAR_WRITE_RELAY_NONCE_HEADER) ?? "";
  const principal = headers.get(GO_SIDECAR_WRITE_RELAY_PRINCIPAL_HEADER) as ManagementPrincipal | null;
  const method = headers.get(GO_SIDECAR_WRITE_RELAY_METHOD_HEADER) as HttpMethod | null;
  const path = headers.get(GO_SIDECAR_WRITE_RELAY_PATH_HEADER) ?? "";
  const expiresAtRaw = headers.get(GO_SIDECAR_WRITE_RELAY_EXPIRES_AT_HEADER) ?? "";
  const proof = headers.get(GO_SIDECAR_WRITE_RELAY_PROOF_HEADER) ?? "";
  if (!BASE64URL_256.test(nonce) || !principal || !PRINCIPALS.has(principal) || !method || !HTTP_METHODS.has(method)) return null;
  if (!PATH.test(path) || !EXPIRY.test(expiresAtRaw) || !BASE64URL_256.test(proof)) return null;
  const expiresAt = Number(expiresAtRaw);
  if (!Number.isSafeInteger(expiresAt)) return null;
  return { nonce, principal, method, path, expiresAt, proof };
}

function relayPayload(claim: Omit<GoSidecarWriteRelayClaim, "proof">, body: Uint8Array): string | null {
  if (!BASE64URL_256.test(claim.nonce) || !PRINCIPALS.has(claim.principal) || !HTTP_METHODS.has(claim.method)) return null;
  if (!PATH.test(claim.path) || !Number.isSafeInteger(claim.expiresAt) || claim.expiresAt <= 0) return null;
  const digest = createHash("sha256").update(body).digest("hex");
  return RELAY_VERSION + "\n" + claim.nonce + "\n" + claim.principal + "\n" + claim.method + "\n" + claim.path + "\n" + digest + "\n" + claim.expiresAt;
}

function verifyProof(secret: string, claim: GoSidecarWriteRelayClaim, body: Uint8Array): boolean {
  const expected = createGoSidecarWriteRelayProof(secret, claim, body);
  return expected !== null && equalSecret(claim.proof, expected);
}

function isRelaySecret(value: string): boolean {
  return BASE64URL_256.test(value);
}

function isBridgeToken(value: string): boolean {
  return value.length > 0 && value.length <= 256 && !/[\r\n]/.test(value);
}

function equalSecret(actual: string | null, expected: string): boolean {
  if (!actual) return false;
  const left = Buffer.from(actual);
  const right = Buffer.from(expected);
  return left.byteLength === right.byteLength && timingSafeEqual(left, right);
}

async function readBoundedBody(request: Request, limit: number): Promise<Uint8Array> {
  const contentLength = Number(request.headers.get("content-length") ?? "0");
  if (Number.isFinite(contentLength) && contentLength > limit) throw new Error("too large");
  const body = new Uint8Array(await request.arrayBuffer());
  if (body.byteLength > limit) throw new Error("too large");
  return body;
}

function pruneConsumed(consumed: Map<string, number>, now: number): void {
  for (const [nonce, expiresAt] of consumed) {
    if (expiresAt <= now) consumed.delete(nonce);
  }
}

function notFound(): Response {
  return new Response(null, { status: 404 });
}
