import type { Capability } from "./capability-types";

export const AGENT_ROUTING_CAPABILITIES: readonly Capability[] = [
  {
    command: ["agent", "status"],
    usage: "ocx agent status [--json]",
    summary: "Read agent mode, delegation, effort caps, roster, fallback and sidecars.",
    routes: [{"method": "GET", "path": "/api/v2"}, {"method": "GET", "path": "/api/injection-model"}, {"method": "GET", "path": "/api/effort-caps"}, {"method": "GET", "path": "/api/subagent-models"}, {"method": "GET", "path": "/api/subagent-model-fallback"}, {"method": "GET", "path": "/api/sidecar-settings"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: false,
    json: "envelope",
    details: [],
  },
  {
    command: ["agent", "effort"],
    usage: "ocx agent effort status [--json]",
    summary: "Read or set main and subagent effort caps.",
    routes: [{"method": "GET", "path": "/api/effort-caps"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: false,
    json: "payload",
    details: ["set requires at least one cap; a null clears it."],
  },
  {
    command: ["agent", "effort", "set"],
    usage: "ocx agent effort set [--main <level|->] [--subagent <level|->] [--json]",
    summary: "Read or set main and subagent effort caps.",
    routes: [{"method": "PUT", "path": "/api/effort-caps"}],
    flags: [{"name": "--main", "value": "string", "summary": "Main effort cap; - clears."}, {"name": "--subagent", "value": "string", "summary": "Subagent effort cap; - clears."}, {"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: true,
    json: "payload",
    details: ["set requires at least one cap; a null clears it."],
  },
  {
    command: ["agent", "subagents"],
    usage: "ocx agent subagents status [--json]",
    summary: "Read, replace or clear the ordered featured subagent roster.",
    routes: [{"method": "GET", "path": "/api/subagent-models"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: false,
    json: "payload",
    details: ["At most five models; clear sends an empty roster. agent roster is an alias."],
  },
  {
    command: ["agent", "subagents", "set"],
    usage: "ocx agent subagents set <model,model...> [--json]",
    summary: "Read, replace or clear the ordered featured subagent roster.",
    routes: [{"method": "PUT", "path": "/api/subagent-models"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: true,
    json: "payload",
    details: ["At most five models; clear sends an empty roster. agent roster is an alias."],
  },
  {
    command: ["agent", "subagents", "clear"],
    usage: "ocx agent subagents clear [--json]",
    summary: "Clear the saved subagents models.",
    routes: [{"method": "PUT", "path": "/api/subagent-models"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: true,
    json: "payload",
    details: ["At most five models; clear sends an empty roster. agent roster is an alias."],
  },
  {
    command: ["agent", "fallback"],
    usage: "ocx agent fallback status [--json]",
    summary: "Read, replace or clear fallback models and polling interval.",
    routes: [{"method": "GET", "path": "/api/subagent-model-fallback"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: false,
    json: "payload",
    details: ["set requires models and/or --poll-ms; clear empties the models and may also set --poll-ms."],
  },
  {
    command: ["agent", "fallback", "set"],
    usage: "ocx agent fallback set [model,model...] [--poll-ms <5000-600000>] [--json]",
    summary: "Read, replace or clear fallback models and polling interval.",
    routes: [{"method": "PUT", "path": "/api/subagent-model-fallback"}],
    flags: [{"name": "--poll-ms", "value": "number", "summary": "Polling interval, 5000-600000 milliseconds."}, {"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: true,
    json: "payload",
    details: ["set requires models and/or --poll-ms; clear empties the models and may also set --poll-ms."],
  },
  {
    command: ["agent", "fallback", "clear"],
    usage: "ocx agent fallback clear [--poll-ms <5000-600000>] [--json]",
    summary: "Clear the saved fallback models.",
    routes: [{"method": "PUT", "path": "/api/subagent-model-fallback"}],
    flags: [{"name": "--poll-ms", "value": "number", "summary": "Polling interval, 5000-600000 milliseconds."}, {"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: true,
    json: "payload",
    details: ["set requires models and/or --poll-ms; clear empties the models and may also set --poll-ms."],
  },
  {
    command: ["agent", "sidecar"],
    usage: "ocx agent sidecar status [--json]",
    summary: "Read configured sidecars and candidate models.",
    routes: [{"method": "GET", "path": "/api/sidecar-settings"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: false,
    json: "payload",
    details: [],
  },
  {
    command: ["agent", "sidecar", "web"],
    usage: "ocx agent sidecar web (--list | [--model <id|->] [--backend <openai|anthropic|xai|gemini|exa|->] [--reasoning <level>] [--max-descriptions <n>] [--enabled <on|off>]) [--json]",
    summary: "List web candidates or change the web sidecar.",
    routes: [{"method": "GET", "path": "/api/sidecar-settings"}, {"method": "PUT", "path": "/api/sidecar-settings"}],
    flags: [{"name": "--list", "value": "boolean", "summary": "Read candidates only; cannot combine with setting flags."}, {"name": "--model", "value": "string", "summary": "Model selector; - clears."}, {"name": "--backend", "value": "string", "summary": "Backend selector; - clears."}, {"name": "--reasoning", "value": "string", "summary": "Reasoning level."}, {"name": "--max-descriptions", "value": "number", "summary": "Positive description limit."}, {"name": "--enabled", "value": "string", "summary": "on or off."}, {"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: true,
    json: "payload",
    details: ["Without --list at least one setting is required. Stored settings and Codex application outcomes remain distinct."],
  },
  {
    command: ["agent", "sidecar", "vision"],
    usage: "ocx agent sidecar vision (--list | [--model <id|->] [--backend <openai|anthropic|routed|->] [--reasoning <level>] [--max-descriptions <n>] [--enabled <on|off>]) [--json]",
    summary: "List vision candidates or change the vision sidecar.",
    routes: [{"method": "GET", "path": "/api/sidecar-settings"}, {"method": "PUT", "path": "/api/sidecar-settings"}],
    flags: [{"name": "--list", "value": "boolean", "summary": "Read candidates only; cannot combine with setting flags."}, {"name": "--model", "value": "string", "summary": "Model selector; - clears."}, {"name": "--backend", "value": "string", "summary": "Backend selector; - clears."}, {"name": "--reasoning", "value": "string", "summary": "Reasoning level."}, {"name": "--max-descriptions", "value": "number", "summary": "Positive description limit."}, {"name": "--enabled", "value": "string", "summary": "on or off."}, {"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: true,
    json: "payload",
    details: ["Without --list at least one setting is required. Stored settings and Codex application outcomes remain distinct."],
  },
  {
    command: ["effort"],
    usage: "ocx effort [status|low|medium|high|xhigh|max|ultra|->] [--json]",
    summary: "Read effort settings or set the main cap with a shorthand level.",
    routes: [{"method": "GET", "path": "/api/effort-caps"}, {"method": "GET", "path": "/api/injection-model"}, {"method": "PUT", "path": "/api/effort-caps"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: true,
    json: "envelope",
    details: ["Uses the live proxy when available, otherwise local config. Once live is selected, errors never fall back to local writes; set reads back live status and can report partial application.", "The shorthand ocx effort <low|medium|high|xhigh|max|ultra|-> changes only the main cap; unset aliases clear."],
  },
  {
    command: ["effort", "set"],
    usage: "ocx effort set [--main <level|->] [--subagent <level|->] [--injection <level|->] [--json]",
    summary: "Set one or more effort fields.",
    routes: [{"method": "PUT", "path": "/api/effort-caps"}, {"method": "PUT", "path": "/api/injection-model"}, {"method": "GET", "path": "/api/effort-caps"}, {"method": "GET", "path": "/api/injection-model"}],
    flags: [{"name": "--main", "value": "string", "summary": "Main cap; - clears."}, {"name": "--subagent", "value": "string", "summary": "Subagent cap; - clears."}, {"name": "--injection", "value": "string", "summary": "Delegation effort; - clears; also accepts none/minimal."}, {"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: true,
    json: "envelope",
    details: ["Local configuration is used when no live proxy is found; runtime failures are not silent offline success."],
  },
  {
    command: ["effort", "clear"],
    usage: "ocx effort clear [--json]",
    summary: "Clear both caps while retaining delegation effort.",
    routes: [{"method": "PUT", "path": "/api/effort-caps"}, {"method": "GET", "path": "/api/effort-caps"}, {"method": "GET", "path": "/api/injection-model"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: true,
    json: "envelope",
    details: ["Local configuration is used when no live proxy is found; runtime failures are not silent offline success."],
  },
  {
    command: ["effort", "model"],
    usage: "ocx effort model <provider/model|model> [--json]",
    summary: "Inspect a model effort ladder and wire mappings from local configuration.",
    routes: [],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local configuration/catalog derivation; routes is empty because no management API is called."],
  },
  {
    command: ["v2", "status"],
    usage: "ocx v2 [status]",
    summary: "Report local multi-agent mode and Codex feature settings.",
    routes: [],
    flags: [],
    mutates: false,
    json: "none",
    details: ["Local config/CODEX_HOME and official Codex feature transition helpers; no management HTTP or --json mode. Changes affect new sessions.", "This command does not claim to update a remote proxy."],
  },
  {
    command: ["v2", "on"],
    usage: "ocx v2 on",
    summary: "Enable the local Codex multi_agent_v2 feature.",
    routes: [],
    flags: [],
    mutates: true,
    json: "none",
    details: ["Local config/CODEX_HOME and official Codex feature transition helpers; no management HTTP or --json mode. Changes affect new sessions.", "Mode/feature changes may resync catalogs; a failed resync does not mean the setting was rolled back."],
  },
  {
    command: ["v2", "off"],
    usage: "ocx v2 off",
    summary: "Disable the local Codex multi_agent_v2 feature.",
    routes: [],
    flags: [],
    mutates: true,
    json: "none",
    details: ["Local config/CODEX_HOME and official Codex feature transition helpers; no management HTTP or --json mode. Changes affect new sessions.", "Mode/feature changes may resync catalogs; a failed resync does not mean the setting was rolled back."],
  },
  {
    command: ["v2", "mode"],
    usage: "ocx v2 mode <v1|default|v2>",
    summary: "Set local model-catalog multi-agent mode.",
    routes: [],
    flags: [],
    mutates: true,
    json: "none",
    details: ["Local config/CODEX_HOME and official Codex feature transition helpers; no management HTTP or --json mode. Changes affect new sessions.", "Mode/feature changes may resync catalogs; a failed resync does not mean the setting was rolled back."],
  },
  {
    command: ["v2", "keep-native-v1"],
    usage: "ocx v2 keep-native-v1 <on|off>",
    summary: "Keep native ChatGPT on v1 while routed models use v2.",
    routes: [],
    flags: [],
    mutates: true,
    json: "none",
    details: ["Local config/CODEX_HOME and official Codex feature transition helpers; no management HTTP or --json mode. Changes affect new sessions.", "Mode/feature changes may resync catalogs; a failed resync does not mean the setting was rolled back."],
  },
  {
    command: ["v2", "threads"],
    usage: "ocx v2 threads <n>",
    summary: "Set the local active-mode thread limit (integer at least 1).",
    routes: [],
    flags: [],
    mutates: true,
    json: "none",
    details: ["Local config/CODEX_HOME and official Codex feature transition helpers; no management HTTP or --json mode. Changes affect new sessions.", "This command does not claim to update a remote proxy."],
  },
  {
    command: ["v2", "mode-hint"],
    usage: "ocx v2 mode-hint <text|--clear>",
    summary: "Set nonblank local delegation hint text or restore effort-derived policy.",
    routes: [],
    flags: [{"name": "--clear", "value": "boolean", "summary": "Unset the hint."}],
    mutates: true,
    json: "none",
    details: ["Local config/CODEX_HOME and official Codex feature transition helpers; no management HTTP or --json mode. Changes affect new sessions.", "This command does not claim to update a remote proxy."],
  },
  {
    command: ["combo", "list"],
    usage: "ocx combo list [--json]",
    summary: "List saved combos.",
    routes: [{"method": "GET", "path": "/api/combos"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: false,
    json: "payload",
    details: [],
  },
  {
    command: ["combo", "show"],
    usage: "ocx combo show <id> [--json]",
    summary: "Read one saved combo from the collection.",
    routes: [{"method": "GET", "path": "/api/combos"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: false,
    json: "payload",
    details: [],
  },
  {
    command: ["combo","set"],
    usage: "ocx combo set <id> [--targets <provider/model[:weight],...> | --targets-file <FILE|->] [--strategy <failover|round-robin|random|least-used|reset-window|jev>] [--sticky <1-100|->] [--effort <low|medium|high|xhigh|max|ultra|->] [--effort-mode <fallback|force|->] [--alias <name|->] [--native-alias [on|off]] [--display-name <label|->] [--decision-provider <provider|-> | --decision-model <route|->] [--decision-timeout <ms|->] [--rename-from <id>] [--image-input <auto|disabled>] [--reasoning-effort-mode <strict|adaptive>] [--json]",
    summary: "Create, update or rename a combo.",
    routes: [{"method":"GET","path":"/api/combos"},{"method":"PUT","path":"/api/combos"}],
    flags: [{"name":"--targets","value":"string","summary":"Ordered provider/model[:weight] list; required for creation."},{"name":"--strategy","value":"string","summary":"Routing strategy."},{"name":"--sticky","value":"string","summary":"Round-robin limit 1-100; - resets."},{"name":"--effort","value":"string","summary":"Default effort; - clears."},{"name":"--effort-mode","value":"string","summary":"fallback or force; - resets to fallback."},{"name":"--alias","value":"string","summary":"Alias; - clears."},{"name":"--display-name","value":"string","summary":"Label; - clears."},{"name":"--decision-provider","value":"string","summary":"JEV provider; - clears."},{"name":"--decision-model","value":"string","summary":"JEV route; - clears; exclusive with provider."},{"name":"--decision-timeout","value":"string","summary":"JEV deadline 1000-120000 ms; - clears."},{"name":"--rename-from","value":"string","summary":"Existing combo ID to rename."},{"name":"--json","value":"boolean","summary":"Emit structured JSON."},{"name":"--native-alias","value":"string","summary":"Bare legacy flag means on; explicit on/off preserves presence, including false."},{"name":"--targets-file","value":"string","summary":"Bounded ordered target JSON array, exclusive with --targets; preserves effort/profile/last-resort metadata."},{"name":"--image-input","value":"string","summary":"auto or disabled; explicit auto clears the previous disabled choice."},{"name":"--reasoning-effort-mode","value":"string","summary":"strict or adaptive, distinct from --effort-mode fallback/force."}],
    mutates: true,
    json: "payload",
    details: ["create and update are aliases of set. Existing fields are read before writing; --targets replaces targets.","force overrides valid client effort and may increase cost and latency.","Only the implemented target grammar is supported; full GUI target metadata and routing-profile writes are separate tasks.","New file/flag conflicts refuse before transport. Partial edits preserve target metadata; explicit false/default values override server carry. Turning a native alias off may also require clearing its incompatible alias.","Read/merge/write uses one target and remains an upsert without revision CAS. Saved-but-incomplete catalog outcomes return nonzero with their receipt."],
  },
  {
    command: ["combo", "remove"],
    usage: "ocx combo remove <id> --yes [--json]",
    summary: "Remove a saved combo after explicit confirmation.",
    routes: [{"method": "DELETE", "path": "/api/combos"}],
    flags: [{"name": "--yes", "value": "boolean", "summary": "Confirm deletion.", "required": true}, {"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: true,
    json: "payload",
    details: ["delete is an alias; the ID is encoded in the id query parameter."],
  },
  {
    command: ["route", "policy", "list"],
    usage: "ocx route policy list [--json]",
    summary: "List saved routing profiles and revisions.",
    routes: [{"method": "GET", "path": "/api/routing-profiles"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: false,
    json: "payload",
    details: [],
  },
  {
    command: ["route", "policy", "show"],
    usage: "ocx route policy show <id> [--json]",
    summary: "Read one saved routing profile.",
    routes: [{"method": "GET", "path": "/api/routing-profiles"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: false,
    json: "payload",
    details: [],
  },
  {
    command: ["route", "policy", "dry-run"],
    usage: "ocx route policy dry-run <id> [--model-context <tokens>] [--tools] [--image] [--structured-output] [--json]",
    summary: "Evaluate a saved profile against explicit requirements without changing it.",
    routes: [{"method": "POST", "path": "/api/routing-profiles/dry-run"}],
    flags: [{"name": "--model-context", "value": "number", "summary": "Positive context window requirement."}, {"name": "--tools", "value": "boolean", "summary": "Require tools."}, {"name": "--image", "value": "boolean", "summary": "Require image input."}, {"name": "--structured-output", "value": "boolean", "summary": "Require structured output."}, {"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: true,
    json: "payload",
    details: ["evaluate and dry-run do not save the profile, but their POST can activate Lab and start automation already enabled by local policy. No profile create, update or delete is exposed."],
  },
  {
    command: ["route", "policy", "evaluate"],
    usage: "ocx route policy evaluate <id> [--model-context <tokens>] [--tools] [--image] [--structured-output] [--json]",
    summary: "Evaluate a saved profile against explicit requirements without changing it.",
    routes: [{"method": "POST", "path": "/api/routing-profiles/dry-run"}],
    flags: [{"name": "--model-context", "value": "number", "summary": "Positive context window requirement."}, {"name": "--tools", "value": "boolean", "summary": "Require tools."}, {"name": "--image", "value": "boolean", "summary": "Require image input."}, {"name": "--structured-output", "value": "boolean", "summary": "Require structured output."}, {"name": "--json", "value": "boolean", "summary": "Emit structured JSON."}],
    mutates: true,
    json: "payload",
    details: ["evaluate and dry-run do not save the profile, but their POST can activate Lab and start automation already enabled by local policy. No profile create, update or delete is exposed."],
  },
  {
    command: ["route","policy","create"],
    usage: "ocx route policy create <id> --file <FILE|-> [--json]",
    summary: "Create a routing profile from an editable-only document.",
    routes: [{"method":"PUT","path":"/api/routing-profiles"}],
    flags: [{"name":"--file","value":"string","summary":"Bounded editable profile JSON; omit show DTO id/model/revision fields.","required":true},{"name":"--json","value":"boolean","summary":"Emit the validated command result as JSON."}],
    mutates: true,
    json: "envelope",
    details: ["The server validates provider/alias/routing relationships and may activate Lab plus automation already enabled on the target. No implicit decision/inference probe follows the save.","An existing ID refuses rather than becoming an update.","Unknown/readonly/nested unsupported file fields refuse; no raw validator issues or file contents are echoed."],
  },
  {
    command: ["route","policy","update"],
    usage: "ocx route policy update <id> --file <FILE|-> --expected-revision <revision> [--json]",
    summary: "Update a routing profile from an editable-only document.",
    routes: [{"method":"PUT","path":"/api/routing-profiles"}],
    flags: [{"name":"--file","value":"string","summary":"Bounded editable profile JSON; omit show DTO id/model/revision fields.","required":true},{"name":"--expected-revision","value":"string","summary":"Exact nonblank revision observed by the caller; never automatically refreshed.","required":true},{"name":"--json","value":"boolean","summary":"Emit the validated command result as JSON."}],
    mutates: true,
    json: "envelope",
    details: ["The server validates provider/alias/routing relationships and may activate Lab plus automation already enabled on the target. No implicit decision/inference probe follows the save.","Stale revision is exit5 with no overwrite/retry; missing profile is exit4.","Unknown/readonly/nested unsupported file fields refuse; no raw validator issues or file contents are echoed."],
  },
  {
    command: ["route","policy","remove"],
    usage: "ocx route policy remove <id> --yes [--json]",
    summary: "Remove one exact routing profile ID.",
    routes: [{"method":"DELETE","path":"/api/routing-profiles"}],
    flags: [{"name":"--yes","value":"boolean","summary":"Explicitly confirm removal.","required":true},{"name":"--json","value":"boolean","summary":"Emit the validated command result as JSON."}],
    mutates: true,
    json: "envelope",
    details: ["Uses the internal stored ID, not a public model alias. DELETE has no revision guard. Saved/catalog outcomes remain distinct; no alternate-target retry."],
  },
  {
    command: ["combo","stats"],
    usage: "ocx combo stats <id> [--range <7d|30d|all>] [--json]",
    summary: "Read JEV decision and token coverage for an exact combo ID.",
    routes: [{"method":"GET","path":"/api/usage"}],
    flags: [{"name":"--range","value":"string","summary":"7d,30d or all; default30d."},{"name":"--json","value":"boolean","summary":"Emit the validated command result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Uses jev=1,comboId and range. Preserves actual counts, nullable averages, measurement coverage and incomplete/truncated history.","No monetary cost or comparative savings baseline exists in this DTO. This is not a decision probe and makes no model inference request."],
  },
];
