import type { Capability } from "./capability-types";

export const INTEGRATION_CAPABILITIES: readonly Capability[] = [
  {
    command: ["grok", "status"],
    usage: "ocx grok status [--json]",
    summary: "Read Grok model fence state and catalog.",
    routes: [{"method": "GET", "path": "/api/grok"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: false,
    json: "payload",
    details: ["integration grok is an alias of grok; show aliases status. Saving selection and applying the saved fence are separate actions.", "Apply receipts can report changed or skippedReason; success is not a guarantee of a changed client file."],
  },
  {
    command: ["grok", "set"],
    usage: "ocx grok set <model,model...> [--json]",
    summary: "Replace the excluded Grok model list.",
    routes: [{"method": "PUT", "path": "/api/grok/selection"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true,
    json: "payload",
    details: ["integration grok is an alias of grok; show aliases status. Saving selection and applying the saved fence are separate actions.", "Apply receipts can report changed or skippedReason; success is not a guarantee of a changed client file."],
  },
  {
    command: ["grok", "exclude"],
    usage: "ocx grok exclude <model,model...> [--json]",
    summary: "Add models to the Grok exclusion list.",
    routes: [{"method": "GET", "path": "/api/grok"}, {"method": "PUT", "path": "/api/grok/selection"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true,
    json: "payload",
    details: ["integration grok is an alias of grok; show aliases status. Saving selection and applying the saved fence are separate actions.", "Apply receipts can report changed or skippedReason; success is not a guarantee of a changed client file."],
  },
  {
    command: ["grok", "include"],
    usage: "ocx grok include <model,model...> [--json]",
    summary: "Remove models from the Grok exclusion list.",
    routes: [{"method": "GET", "path": "/api/grok"}, {"method": "PUT", "path": "/api/grok/selection"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true,
    json: "payload",
    details: ["integration grok is an alias of grok; show aliases status. Saving selection and applying the saved fence are separate actions.", "Apply receipts can report changed or skippedReason; success is not a guarantee of a changed client file."],
  },
  {
    command: ["grok", "clear"],
    usage: "ocx grok clear [--json]",
    summary: "Clear Grok exclusions.",
    routes: [{"method": "PUT", "path": "/api/grok/selection"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true,
    json: "payload",
    details: ["integration grok is an alias of grok; show aliases status. Saving selection and applying the saved fence are separate actions.", "Apply receipts can report changed or skippedReason; success is not a guarantee of a changed client file."],
  },
  {
    command: ["grok", "apply"],
    usage: "ocx grok apply [--json]",
    summary: "Apply the saved Grok model fence.",
    routes: [{"method": "POST", "path": "/api/grok/apply"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true,
    json: "payload",
    details: ["integration grok is an alias of grok; show aliases status. Saving selection and applying the saved fence are separate actions.", "Apply receipts can report changed or skippedReason; success is not a guarantee of a changed client file."],
  },
  {
    command: ["integration", "client", "status"],
    usage: "ocx integration client status [--client <id>] [--profile <id>] [--json]",
    summary: "Read all file integrations, one client or an Aside profile.",
    routes: [{"method": "GET", "path": "/api/client-integrations"}, {"method": "GET", "path": "/api/client-integrations/{clientId}"}, {"method": "GET", "path": "/api/client-integrations/aside/profiles"}, {"method": "GET", "path": "/api/client-integrations/aside/profiles/{profileId}"}],
    flags: [{"name": "--client", "value": "string", "summary": "File integration ID; aside selects profiles."}, {"name": "--profile", "value": "number", "summary": "Aside nonnegative integer account ID; requires --client aside."}, {"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: false,
    json: "payload",
    details: ["show and list alias status; omitted Aside profile means the aggregate profile collection."],
  },
  {
    command: ["integration", "client", "history"],
    usage: "ocx integration client history [--client <id>] [--profile <id>] [--json]",
    summary: "Read integration rollback history and snapshot availability.",
    routes: [{"method": "GET", "path": "/api/client-integrations/journal"}, {"method": "GET", "path": "/api/client-integrations/aside/profiles/journal"}, {"method": "GET", "path": "/api/client-integrations/aside/profiles/{profileId}/journal"}],
    flags: [{"name": "--client", "value": "string", "summary": "File integration ID; aside selects profiles."}, {"name": "--profile", "value": "number", "summary": "Aside nonnegative integer account ID; requires --client aside."}, {"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: false,
    json: "payload",
    details: ["journal is an alias. Ordinary client filtering uses ?client=; expired snapshots remain visibly expired."],
  },
  {
    command: ["integration", "client", "enable"],
    usage: "ocx integration client enable --client <id> [--profile <id>] [--overwrite-conflict] [--json]",
    summary: "Apply the selected managed file integration.",
    routes: [{"method": "PUT", "path": "/api/client-integrations/{clientId}"}, {"method": "PUT", "path": "/api/client-integrations/aside/profiles"}, {"method": "PUT", "path": "/api/client-integrations/aside/profiles/{profileId}"}],
    flags: [{"name": "--client", "value": "string", "summary": "Explicit file integration ID.", "required": true}, {"name": "--profile", "value": "number", "summary": "Aside nonnegative integer account ID; requires --client aside."}, {"name": "--overwrite-conflict", "value": "boolean", "summary": "Explicitly permit replacing a conflicting block."}, {"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true,
    json: "payload",
    details: ["An omitted Aside profile toggles all Aside profiles. Ownership, snapshots, journal and conflict refusals remain server-owned.", "Partial Aside failures remain failures after emitting the per-profile result. Never infer permission to overwrite from a refusal."],
  },
  {
    command: ["integration", "client", "disable"],
    usage: "ocx integration client disable --client <id> [--profile <id>] [--json]",
    summary: "Disable the selected managed file integration.",
    routes: [{"method": "PUT", "path": "/api/client-integrations/{clientId}"}, {"method": "PUT", "path": "/api/client-integrations/aside/profiles"}, {"method": "PUT", "path": "/api/client-integrations/aside/profiles/{profileId}"}],
    flags: [{"name": "--client", "value": "string", "summary": "Explicit file integration ID.", "required": true}, {"name": "--profile", "value": "number", "summary": "Aside nonnegative integer account ID; requires --client aside."}, {"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true,
    json: "payload",
    details: ["An omitted Aside profile toggles all Aside profiles. Ownership, snapshots, journal and conflict refusals remain server-owned.", "Partial Aside failures remain failures after emitting the per-profile result. Never infer permission to overwrite from a refusal."],
  },
  {
    command: ["integration", "client", "restore"],
    usage: "ocx integration client restore --op <opId> [--client aside --profile <id>] [--confirm-drift] [--json]",
    summary: "Restore a selected rollback operation, retaining drift refusal.",
    routes: [{"method": "POST", "path": "/api/client-integrations/restore"}, {"method": "POST", "path": "/api/client-integrations/aside/profiles/{profileId}/restore"}],
    flags: [{"name": "--op", "value": "string", "summary": "Operation ID; --op-id is an alias.", "required": true}, {"name": "--client", "value": "string", "summary": "File integration ID; aside selects profiles."}, {"name": "--profile", "value": "number", "summary": "Aside nonnegative integer account ID; requires --client aside."}, {"name": "--confirm-drift", "value": "boolean", "summary": "Explicitly allow replacing edits made after the snapshot."}, {"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true,
    json: "payload",
    details: ["With --client, restore requires --profile; only Aside profiles accept that selector. No automatic drift confirmation or retry."],
  },
  {
    command: ["claude", "config", "status"],
    usage: "ocx claude config status [--json]",
    summary: "Read effective Claude Code configuration.",
    routes: [{"method": "GET", "path": "/api/claude-code"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: false,
    json: "payload",
    details: ["show is an alias; integration claude forwards to the same handler."],
  },
  {
    command: ["claude", "config", "set"],
    usage: "ocx claude config set [--enabled <on|off>] [--auth-mode <auto|proxy|subscription>] [--system-env <on|off>] [--fast-mode <on|off>] [--auto-context <on|off>] [--compact-window <tokens|default>] [--inject-agents <on|off>] [--small-fast-model <id|->] [--model-map <from=to,...|->] [--blocked-skills <name,name|->] [--web-model <id|->] [--web-backend <openai|anthropic|xai|gemini|exa|->] [--vision-model <id|->] [--vision-backend <openai|anthropic|->] [--json]; or ocx claude config set --first-party <on|off> [--json]",
    summary: "Change Claude Code settings through the runtime owner.",
    routes: [{"method": "PUT", "path": "/api/claude-code"}],
    flags: [{"name": "--enabled", "value": "string", "summary": "on or off."}, {"name": "--auth-mode", "value": "string", "summary": "auto, proxy or subscription."}, {"name": "--system-env", "value": "string", "summary": "on or off."}, {"name": "--fast-mode", "value": "string", "summary": "on or off."}, {"name": "--auto-context", "value": "string", "summary": "on or off."}, {"name": "--compact-window", "value": "string", "summary": "Positive token count or default to clear."}, {"name": "--inject-agents", "value": "string", "summary": "on or off."}, {"name": "--small-fast-model", "value": "string", "summary": "Model ID; - clears."}, {"name": "--model-map", "value": "string", "summary": "Comma-separated from=to mappings; - clears."}, {"name": "--blocked-skills", "value": "string", "summary": "Comma-separated names; - clears."}, {"name": "--web-model", "value": "string", "summary": "Model ID; - clears."}, {"name": "--web-backend", "value": "string", "summary": "openai, anthropic, xai, gemini, exa or -."}, {"name": "--vision-model", "value": "string", "summary": "Model ID; - clears."}, {"name": "--vision-backend", "value": "string", "summary": "openai, anthropic or -."}, {"name": "--first-party", "value": "string", "summary": "on or off; must be the only setting."}, {"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true,
    json: "payload",
    details: ["At least one setting is required. --first-party must be set alone and writes Claude settings immediately.", "Clear both helper model and backend with - to restore inheritance. Preserve shared_proxy_retained warnings."],
  },
  {
    command: ["claude", "desktop", "show"],
    usage: "ocx claude desktop show [--json]",
    summary: "Inspect the desired profile derived on this machine.",
    routes: [],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local config/catalog derivation, not GET of the remote desired profile. On a connected client scope is local; apply uses the hub profile. Catalog derivation may discover upstream models."],
  },
  {
    command: ["claude", "desktop", "move"],
    usage: "ocx claude desktop move <provider/model> <opus|fable|sonnet|haiku> [--default]",
    summary: "Move an available route to a local Desktop family.",
    routes: [],
    flags: [{"name": "--default", "value": "boolean", "summary": "Make this route the family default."}],
    mutates: true,
    json: "none",
    details: ["Local profile persistence only; no management HTTP or --json. On connected clients this does not change the hub profile."],
  },
  {
    command: ["claude", "desktop", "default"],
    usage: "ocx claude desktop default <opus|fable|sonnet|haiku> <provider/model|none>",
    summary: "Set or clear a local Desktop family default.",
    routes: [],
    flags: [],
    mutates: true,
    json: "none",
    details: ["Local profile persistence only; none clears the default. Connected Desktop apply uses the hub profile."],
  },
  {
    command: ["claude", "desktop", "export"],
    usage: "ocx claude desktop export <path|->",
    summary: "Export the persisted local Desktop profile.",
    routes: [],
    flags: [],
    mutates: true,
    json: "none",
    details: ["Local file output; - writes JSON to stdout. There is no --json flag. A file destination is overwritten; this is not a GUI draft export."],
  },
  {
    command: ["claude", "desktop", "import"],
    usage: "ocx claude desktop import <path> [--apply]",
    summary: "Import a local Desktop profile, optionally applying it as a static gateway.",
    routes: [{"method": "POST", "path": "/api/claude-desktop/apply"}],
    flags: [{"name": "--apply", "value": "boolean", "summary": "After saving, apply as a static gateway."}],
    mutates: true,
    json: "none",
    details: ["Without --apply this only persists locally. With a live local proxy, gateway apply is delegated by HTTP; otherwise local helpers apply it.", "Connected clients refuse import --apply. A saved profile can remain saved after application fails; no --json mode."],
  },
  {
    command: ["claude", "desktop", "apply"],
    usage: "ocx claude desktop [apply] [--first-party | --gateway [--static|--hybrid|--discovery-only]]",
    summary: "Apply Claude Desktop first-party interception or gateway profile.",
    routes: [{"method": "POST", "path": "/api/claude-desktop/apply"}],
    flags: [{"name": "--first-party", "value": "boolean", "summary": "Keep Desktop on claude.ai and intercept its Code tab."}, {"name": "--gateway", "value": "boolean", "summary": "Apply a third-party gateway profile."}, {"name": "--static", "value": "boolean", "summary": "Static gateway model catalog."}, {"name": "--hybrid", "value": "boolean", "summary": "Hybrid gateway catalog."}, {"name": "--discovery-only", "value": "boolean", "summary": "Discovery-only gateway catalog."}],
    mutates: true,
    json: "none",
    details: ["Uses local helpers or the live local apply route; connected gateway clients use the hub profile download path. No --json mode.", "First-party requires a local hub with interception enabled. Preserve account-risk warnings, trust prompts and ownership refusals; metadata grants no consent.", "Application and committed-marker persistence can diverge; inspect status after application and preserve warnings."],
  },
];
