import type { Capability } from "./capability-types";

/** Verified existing handlers only; local operations never claim management routes. */
export const ACCESS_REMOTE_CAPABILITIES: readonly Capability[] = [
  {
    command: ["access", "key"], summary: "Manage API access keys and inspect masked metadata.",
    usage: "ocx access key list [--json]",
    routes: [{"method": "GET", "path": "/api/keys"}, {"method": "POST", "path": "/api/keys"}, {"method": "PATCH", "path": "/api/keys"}, {"method": "DELETE", "path": "/api/keys"}, {"method": "POST", "path": "/api/keys/rotate"}, {"method": "POST", "path": "/api/keys/rotate/commit"}, {"method": "DELETE", "path": "/api/keys/rotate"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true, json: "payload",
    details: ["Mixed family: list/get read masked metadata; scope edits, revocation and rotation change authorization.", "Creation and rotation initiation return plaintext secrets once and are human-only handoffs. Ask the operator to perform them in their terminal or dashboard; never capture the returned credential.", "Use the separately documented safe follow-up leaves. keys and top-level api-key are aliases."],
  },
  {
    command: ["access", "key", "list"], summary: "List masked access keys, usage, endpoints and pending rotations.",
    usage: "ocx access key list [--json]",
    routes: [{"method": "GET", "path": "/api/keys"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: false, json: "payload",
    details: ["No plaintext secret is returned by the list route."],
  },
  {
    command: ["access", "key", "get"], summary: "Read one masked key and its access scope.",
    usage: "ocx access key get <id-or-name> [--json]",
    routes: [{"method": "GET", "path": "/api/keys"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: false, json: "payload",
    details: ["Case-insensitive ID takes precedence over name; ambiguous names are refused."],
  },
  {
    command: ["access", "key", "set"], summary: "Replace selected provider/model scope dimensions.",
    usage: "ocx access key set <id-or-name> [--allow-provider <name>]... [--allow-model <id>]... [--clear] [--json]",
    routes: [{"method": "GET", "path": "/api/keys"}, {"method": "PATCH", "path": "/api/keys"}],
    flags: [{"name": "--allow-provider", "value": "string", "summary": "Provider scope; repeatable, replaces that dimension."}, {"name": "--allow-model", "value": "string", "summary": "Model scope; repeatable, replaces that dimension."}, {"name": "--clear", "value": "boolean", "summary": "Clear both dimensions; submitted allow options then override their dimension."}, {"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true, json: "payload",
    details: ["At least one scope option is required. Unspecified dimensions are preserved; this command does not rename keys."],
  },
  {
    command: ["access", "key", "rotate", "commit"], summary: "Commit a pending key rotation.",
    usage: "ocx access key rotate commit <id> <rotation-id> [--json]",
    routes: [{"method": "POST", "path": "/api/keys/rotate/commit"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true, json: "payload",
    details: ["Use IDs from the human-authorized rotation. Commit only after the client accepts the replacement; the old credential is retired."],
  },
  {
    command: ["access", "key", "rotate", "abort"], summary: "Abort a pending key rotation.",
    usage: "ocx access key rotate abort <id> <rotation-id> [--json]",
    routes: [{"method": "DELETE", "path": "/api/keys/rotate"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true, json: "payload",
    details: ["Use IDs from the human-authorized rotation. Abort discards the pending replacement credential."],
  },
  {
    command: ["access", "key", "remove"], summary: "Revoke one API access key.",
    usage: "ocx access key remove <id> --yes [--json]",
    routes: [{"method": "DELETE", "path": "/api/keys"}],
    flags: [{"name": "--yes", "value": "boolean", "summary": "Required confirmation before revoking the key.", "required": true}, {"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true, json: "payload",
    details: ["Uses the exact ID, not name resolution; delete is an alias."],
  },
  {
    command: ["access", "endpoints"], summary: "Read endpoint URLs from the access-key metadata.",
    usage: "ocx access endpoints [--json]",
    routes: [{"method": "GET", "path": "/api/keys"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: false, json: "envelope",
    details: ["Projects only baseUrl, endpoint and fields ending in Endpoint; use key list for the full metadata payload."],
  },
  {
    command: ["access", "models"], summary: "Read the public external-model catalog.",
    usage: "ocx access models [--json]",
    routes: [],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: false, json: "payload",
    details: ["Data-plane GET /v1/models via the runtime client; differs from management models live. The routes field indexes management API routes only."],
  },
  {
    command: ["access", "test"], summary: "Send a small inference request through the selected protocol.",
    usage: "ocx access test <model> [--protocol <chat|responses|messages>] [--json]",
    routes: [],
    flags: [{"name": "--protocol", "value": "string", "summary": "chat | responses | messages; default chat."}, {"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true, json: "payload",
    details: ["Data-plane POST /v1/chat/completions, /v1/responses or /v1/messages according to --protocol; these are not management API routes. May spend upstream quota; run only for an explicitly authorized inference probe.", "Uses runtime management headers and has no chosen-key input; success is not validation of a newly created data key."],
  },
  {
    command: ["remote-workspace","hub","status"],
    usage: "ocx remote-workspace hub status [--json]",
    summary: "Read Hub devices, runtime availability and sessions.",
    routes: [{"method":"GET","path":"/api/remote-workspace"}],
    flags: [{"name":"--json","value":"boolean","summary":"Emit one validated task result as JSON."}],
    mutates: false,
    json: "payload",
    details: ["Existing remote-workspace status remains executor-local. These fixed reads use the selected management Hub; they do not create pairing grants, sessions or remote commands.","Available empty lists succeed. Disabled Hub observations return explicit available:false and exit1; malformed or refused responses are not presented as empty success. Runtime reads can perform availability probes."],
  },
  {
    command: ["remote-workspace","hub","runtimes"],
    usage: "ocx remote-workspace hub runtimes [--json]",
    summary: "Read Codex, Claude and Pi availability on the Hub.",
    routes: [{"method":"GET","path":"/api/remote-workspace/runtimes"}],
    flags: [{"name":"--json","value":"boolean","summary":"Emit one validated task result as JSON."}],
    mutates: false,
    json: "payload",
    details: ["Existing remote-workspace status remains executor-local. These fixed reads use the selected management Hub; they do not create pairing grants, sessions or remote commands.","Available empty lists succeed. Disabled Hub observations return explicit available:false and exit1; malformed or refused responses are not presented as empty success. Runtime reads can perform availability probes."],
  },
  {
    command: ["remote-workspace","hub","sessions"],
    usage: "ocx remote-workspace hub sessions [--json]",
    summary: "Read Hub sessions and their public recent events.",
    routes: [{"method":"GET","path":"/api/remote-workspace/sessions"}],
    flags: [{"name":"--json","value":"boolean","summary":"Emit one validated task result as JSON."}],
    mutates: false,
    json: "payload",
    details: ["Existing remote-workspace status remains executor-local. These fixed reads use the selected management Hub; they do not create pairing grants, sessions or remote commands.","Available empty lists succeed. Disabled Hub observations return explicit available:false and exit1; malformed or refused responses are not presented as empty success. Runtime reads can perform availability probes."],
  },
];
