package ocxcli

// opencode_golden_test.go — engine golden constants captured from the TS
// launcher (src/cli/opencode.ts) by /tmp/oc_opencode_golden.ts on 2026-09-09.
// Regenerate by running that probe with bun and re-emitting this file.
// Re-running the TS engine is the oracle; these bytes are its frozen output.

const goldenCatalog = `[{"namespaced":"provider2/model-b","native":false,"provider":"provider2","id":"model-b","contextWindow":64000,"reasoningEfforts":["low","high"]},{"namespaced":"openai/gpt-5.2","native":true,"provider":"openai","id":"gpt-5.2","contextWindow":300000},{"namespaced":"provider1/model-a","native":false,"provider":"provider1","id":"model-a","contextWindow":128000,"displayName":"Model A","reasoningEfforts":["none","high"],"defaultReasoningEffort":"high"},{"namespaced":"noctx/provider","native":false,"provider":"noctx","id":"provider"}]`

const goldenV1 = `{"npm":"@ai-sdk/openai-compatible","name":"OpenCodex","options":{"baseURL":"http://127.0.0.1:10100/v1","apiKey":"{env:OPENCODEX_OPENCODE_API_KEY}"},"models":{"provider2/model-b":{"name":"model-b (provider2)","limit":{"context":64000,"output":32000}},"openai/gpt-5.2":{"name":"gpt-5.2 (native)","limit":{"context":300000,"output":32000}},"provider1/model-a":{"name":"Model A (provider1)","limit":{"context":128000,"output":32000}},"noctx/provider":{"name":"provider (noctx)"}}}`

const goldenV2 = `{"package":"@opencode-ai/ai/providers/openai-compatible","name":"OpenCodex","settings":{"baseURL":"http://127.0.0.1:10100/v1","apiKey":"{env:OPENCODEX_OPENCODE_API_KEY}"},"models":{"provider2/model-b":{"name":"model-b (provider2)","limit":{"context":64000,"output":32000},"variants":[{"id":"low","settings":{"reasoningEffort":"low"}},{"id":"high","settings":{"reasoningEffort":"high"}}]},"openai/gpt-5.2":{"name":"gpt-5.2 (native)","limit":{"context":300000,"output":32000}},"provider1/model-a":{"name":"Model A (provider1)","limit":{"context":128000,"output":32000},"variants":[{"id":"high","settings":{"reasoningEffort":"high"}}]},"noctx/provider":{"name":"provider (noctx)"}}}`

const goldenContent = `{"$schema":"https://opencode.ai/config.json","provider":{"opencodex":{"npm":"@ai-sdk/openai-compatible","name":"OpenCodex","options":{"baseURL":"http://127.0.0.1:10100/v1","apiKey":"{env:OPENCODEX_OPENCODE_API_KEY}"},"models":{"provider2/model-b":{"name":"model-b (provider2)","limit":{"context":64000,"output":32000}},"openai/gpt-5.2":{"name":"gpt-5.2 (native)","limit":{"context":300000,"output":32000}},"provider1/model-a":{"name":"Model A (provider1)","limit":{"context":128000,"output":32000}},"noctx/provider":{"name":"provider (noctx)"}}}},"providers":{"opencodex":{"package":"@opencode-ai/ai/providers/openai-compatible","name":"OpenCodex","settings":{"baseURL":"http://127.0.0.1:10100/v1","apiKey":"{env:OPENCODEX_OPENCODE_API_KEY}"},"models":{"provider2/model-b":{"name":"model-b (provider2)","limit":{"context":64000,"output":32000},"variants":[{"id":"low","settings":{"reasoningEffort":"low"}},{"id":"high","settings":{"reasoningEffort":"high"}}]},"openai/gpt-5.2":{"name":"gpt-5.2 (native)","limit":{"context":300000,"output":32000}},"provider1/model-a":{"name":"Model A (provider1)","limit":{"context":128000,"output":32000},"variants":[{"id":"high","settings":{"reasoningEffort":"high"}}]},"noctx/provider":{"name":"provider (noctx)"}}}}}`

const goldenInherited = `{"$schema":"https://custom.test/config.json","theme":"dark","provider":{"other":{"npm":"x"},"opencodex":{"npm":"@ai-sdk/openai-compatible","name":"OpenCodex","options":{"baseURL":"http://127.0.0.1:10100/v1","apiKey":"{env:OPENCODEX_OPENCODE_API_KEY}"},"models":{"provider2/model-b":{"name":"model-b (provider2)","limit":{"context":64000,"output":32000}},"openai/gpt-5.2":{"name":"gpt-5.2 (native)","limit":{"context":300000,"output":32000}},"provider1/model-a":{"name":"Model A (provider1)","limit":{"context":128000,"output":32000}},"noctx/provider":{"name":"provider (noctx)"}}}},"providers":{"legacy":{"package":"y"},"opencodex":{"package":"@opencode-ai/ai/providers/openai-compatible","name":"OpenCodex","settings":{"baseURL":"http://127.0.0.1:10100/v1","apiKey":"{env:OPENCODEX_OPENCODE_API_KEY}"},"models":{"provider2/model-b":{"name":"model-b (provider2)","limit":{"context":64000,"output":32000},"variants":[{"id":"low","settings":{"reasoningEffort":"low"}},{"id":"high","settings":{"reasoningEffort":"high"}}]},"openai/gpt-5.2":{"name":"gpt-5.2 (native)","limit":{"context":300000,"output":32000}},"provider1/model-a":{"name":"Model A (provider1)","limit":{"context":128000,"output":32000},"variants":[{"id":"high","settings":{"reasoningEffort":"high"}}]},"noctx/provider":{"name":"provider (noctx)"}}}}}`
