package ocxcli

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// TestParsePidFileTypeScriptMatrix pins the Go parser to the exact TypeScript
// parsePidFile matrix (generated by running src/config/process-state.ts
// semantics through bun, including randomized input). Both sides must agree
// on every row: this gate decides whether a recorded PID is acted upon.
func TestParsePidFileTypeScriptMatrix(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "pid-parse-oracle.tsv"))
	if err != nil {
		t.Fatalf("read oracle: %v", err)
	}
	for _, line := range strings.Split(strings.TrimRight(string(raw), "\n"), "\n") {
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, "\t", 2)
		if len(parts) != 2 {
			t.Fatalf("oracle row not <json>\t<value>: %q", line)
		}
		var input string
		if err := json.Unmarshal([]byte(parts[0]), &input); err != nil {
			t.Fatalf("decode oracle input %q: %v", parts[0], err)
		}
		want := int64(0)
		if parts[1] != "null" {
			value, err := strconv.ParseInt(parts[1], 10, 64)
			if err != nil {
				t.Fatalf("decode oracle value %q: %v", parts[1], err)
			}
			want = value
		}
		if got := parsePidFile(input); got != want {
			t.Errorf("parsePidFile(%q) = %d, TypeScript says %d", input, got, want)
		}
	}
}
