type Locale = "en" | "ko" | "de" | "fr" | "zh" | "zh-TW" | "ru" | "ja" | "tr" | "vi";
const locales: readonly Locale[] = ["en", "ko", "de", "fr", "zh", "zh-TW", "ru", "ja", "tr", "vi"];
type Row = readonly [string, string, string, string, string, string, string, string, string, string];
const rows = {
  connectionUnavailable: ["The saved local connection could not be opened. Its address was not changed automatically.", "저장된 로컬 연결을 열지 못했습니다. 연결 주소를 자동으로 변경하지 않았습니다.", "Die gespeicherte lokale Verbindung konnte nicht geöffnet werden. Ihre Adresse wurde nicht automatisch geändert.", "La connexion locale enregistrée n’a pas pu être ouverte. Son adresse n’a pas été modifiée automatiquement.", "无法打开保存的本地连接。未自动更改其地址。", "無法開啟儲存的本機連線。並未自動變更其位址。", "Не удалось открыть сохранённое локальное соединение. Его адрес автоматически не менялся.", "保存されたローカル接続を開けませんでした。接続先を自動変更していません。", "Kaydedilen yerel bağlantı açılamadı. Adresi otomatik değiştirilmedi.", "Không mở được kết nối cục bộ đã lưu. Địa chỉ không được tự động thay đổi."],
  blockedByBuild: ["This Codex build has not been assessed. Compatibility correction is unavailable; refresh alone will not enable it.", "현재 Codex 빌드는 아직 검증되지 않았습니다. 호환 교정을 사용할 수 없으며, 새로고침만으로 활성화되지는 않습니다.", "Dieser Codex-Build wurde noch nicht geprüft. Die Kompatibilitätskorrektur ist nicht verfügbar; Aktualisieren allein aktiviert sie nicht.", "Cette version de Codex n’a pas été évaluée. La correction est indisponible ; une actualisation seule ne l’activera pas.", "此 Codex 版本尚未评估。兼容修正不可用，刷新不会启用它。", "此 Codex 版本尚未評估。相容修正無法使用，重新整理不會啟用它。", "Эта сборка Codex не проверена. Коррекция недоступна; обновление состояния её не включит.", "この Codex ビルドは未検証です。互換補正は利用できず、状態更新だけでは有効になりません。", "Bu Codex derlemesi henüz değerlendirilmedi. Uyumluluk düzeltmesi kullanılamaz; yenileme bunu açmaz.", "Bản Codex này chưa được đánh giá. Chưa thể hiệu chỉnh; làm mới không tự bật tính năng."],
  blockedByProxy: ["This integration does not yet support the configured outbound proxy. It has not bypassed that proxy.", "설정된 외부 프록시를 아직 지원하지 않습니다. 해당 프록시를 우회하지 않았습니다.", "Der konfigurierte ausgehende Proxy wird noch nicht unterstützt. Er wurde nicht umgangen.", "Le proxy sortant configuré n’est pas encore pris en charge. Il n’a pas été contourné.", "尚不支持配置的出站代理。未绕过该代理。", "尚不支援設定的輸出代理。並未繞過該代理。", "Настроенный исходящий прокси пока не поддерживается. Он не был обойдён.", "設定された送信プロキシには未対応です。プロキシの迂回は行っていません。", "Ayarlanan çıkış proxy’si henüz desteklenmiyor. Proxy atlanmadı.", "Chưa hỗ trợ proxy đầu ra đã cấu hình. Không bỏ qua proxy đó."],
  closeApp: ["Save drafts, close Codex, then refresh status before trying again.", "초안을 저장하고 Codex를 닫은 뒤 상태를 새로고침하여 재시도하세요.", "Entwürfe speichern, Codex schließen und vor dem nächsten Versuch den Status aktualisieren.", "Enregistrez les brouillons, fermez Codex, puis actualisez l’état avant de réessayer.", "保存草稿并关闭 Codex，然后刷新状态再重试。", "儲存草稿並關閉 Codex，然後重新整理狀態再重試。", "Сохраните черновики, закройте Codex и обновите состояние перед повтором.", "下書きを保存して Codex を閉じ、状態を更新してから再試行してください。", "Taslakları kaydedip Codex’i kapatın; yeniden denemeden önce durumu yenileyin.", "Lưu bản nháp, đóng Codex rồi làm mới trạng thái trước khi thử lại."],
  connectedUnavailable: ["These local controls are unavailable in OpenCodex managed client mode.", "OpenCodex 관리형 클라이언트 모드에서는 이 로컬 제어를 사용할 수 없습니다.", "Diese lokalen Steuerelemente sind im verwalteten Clientmodus von OpenCodex nicht verfügbar.", "Ces commandes locales ne sont pas disponibles en mode client géré OpenCodex.", "OpenCodex 托管客户端模式不提供这些本地控制。", "OpenCodex 受管理用戶端模式不提供這些本機控制。", "Эти локальные действия недоступны в управляемом клиентском режиме OpenCodex.", "OpenCodex の管理対象クライアントモードでは、このローカル操作を利用できません。", "Bu yerel denetimler OpenCodex yönetilen istemci modunda kullanılamaz.", "Các điều khiển cục bộ này không có trong chế độ máy khách được quản lý của OpenCodex."],
  title: ["Desktop compatibility", "데스크톱 호환", "Desktop-Kompatibilität", "Compatibilité du bureau", "桌面兼容", "桌面相容", "Совместимость приложения", "デスクトップ互換性", "Masaüstü uyumluluğu", "Tương thích ứng dụng"],
  description: ["Experimental Windows integration. Keeps the Codex login; setup alone does not enable correction.", "실험적인 Windows 연동입니다. Codex 로그인을 유지하며, 준비만으로 교정이 켜지지 않습니다.", "Experimentelle Windows-Integration. Die Codex-Anmeldung bleibt erhalten; die Einrichtung aktiviert keine Korrektur.", "Intégration Windows expérimentale. La connexion Codex est conservée ; la préparation seule n’active pas la correction.", "实验性 Windows 集成。保留 Codex 登录；仅完成准备不会启用修正。", "實驗性 Windows 整合。保留 Codex 登入；僅完成準備不會啟用修正。", "Экспериментальная интеграция Windows. Вход в Codex сохраняется; подготовка не включает коррекцию.", "実験的な Windows 連携です。Codex のログインを保持し、準備だけでは補正を有効にしません。", "Deneysel Windows entegrasyonu. Codex oturumu korunur; hazırlık tek başına düzeltmeyi açmaz.", "Tích hợp Windows thử nghiệm. Giữ đăng nhập Codex; chuẩn bị không tự bật hiệu chỉnh."],
  refresh: ["Refresh status", "상태 새로고침", "Status aktualisieren", "Actualiser l’état", "刷新状态", "重新整理狀態", "Обновить состояние", "状態を更新", "Durumu yenile", "Làm mới trạng thái"],
  prepare: ["Prepare certificate", "인증서 준비", "Zertifikat vorbereiten", "Préparer le certificat", "准备证书", "準備憑證", "Подготовить сертификат", "証明書を準備", "Sertifikayı hazırla", "Chuẩn bị chứng chỉ"],
  trust: ["Register trust", "신뢰 등록", "Vertrauen registrieren", "Enregistrer la confiance", "注册信任", "註冊信任", "Добавить доверие", "信頼を登録", "Güveni kaydet", "Đăng ký tin cậy"],
  remove: ["Remove trust", "신뢰 해제", "Vertrauen entfernen", "Retirer la confiance", "移除信任", "移除信任", "Удалить доверие", "信頼を解除", "Güveni kaldır", "Gỡ tin cậy"],
  renew: ["Renew certificate", "인증서 갱신", "Zertifikat erneuern", "Renouveler le certificat", "更新证书", "更新憑證", "Обновить сертификат", "証明書を更新", "Sertifikayı yenile", "Gia hạn chứng chỉ"],
  start: ["Start observation", "관찰 시작", "Beobachtung starten", "Démarrer l’observation", "开始观察", "開始觀察", "Начать наблюдение", "観察を開始", "Gözlemi başlat", "Bắt đầu quan sát"],
  stop: ["Stop service", "서비스 중지", "Dienst stoppen", "Arrêter le service", "停止服务", "停止服務", "Остановить службу", "サービスを停止", "Hizmeti durdur", "Dừng dịch vụ"],
  launch: ["Open Codex", "Codex 열기", "Codex öffnen", "Ouvrir Codex", "打开 Codex", "開啟 Codex", "Открыть Codex", "Codex を開く", "Codex’i aç", "Mở Codex"],
  observe: ["Return to observation", "관찰 모드로 복귀", "Zur Beobachtung zurück", "Revenir à l’observation", "返回观察", "返回觀察", "Вернуться к наблюдению", "観察に戻る", "Gözleme dön", "Trở lại quan sát"],
  apply: ["Run 3-minute trial", "3분 복구 시험", "3-Minuten-Test starten", "Essai de 3 minutes", "运行 3 分钟试验", "執行 3 分鐘試驗", "Запустить тест на 3 минуты", "3分間のテスト", "3 dakikalık deneme", "Thử nghiệm 3 phút"],
  confirm: ["Confirm action", "동작 확인", "Aktion bestätigen", "Confirmer l’action", "确认操作", "確認操作", "Подтвердить действие", "操作を確認", "İşlemi onayla", "Xác nhận thao tác"],
  acknowledge: ["I understand the scope of this action.", "이 동작의 적용 범위를 이해했습니다.", "Ich verstehe den Umfang dieser Aktion.", "Je comprends la portée de cette action.", "我了解此操作的范围。", "我了解此操作的範圍。", "Я понимаю область действия.", "この操作の範囲を理解しました。", "Bu işlemin kapsamını anlıyorum.", "Tôi hiểu phạm vi thao tác này."],
  risk: ["Trust applies to this Windows user and allows the local relay to handle chatgpt.com traffic. Stop the service and close Codex before renewal or removal. Stopping may interrupt active connections.", "이 Windows 사용자에게 인증서 신뢰가 적용되어 로컬 릴레이가 chatgpt.com 트래픽을 처리합니다. 갱신·해제 전 서비스를 중지하고 Codex를 닫으세요. 중지하면 진행 중인 연결이 끊길 수 있습니다.", "Das Vertrauen gilt für diesen Windows-Benutzer und erlaubt dem lokalen Relay, chatgpt.com-Verkehr zu verarbeiten. Vor Erneuerung oder Entfernung Dienst stoppen und Codex schließen. Ein Stopp kann aktive Verbindungen unterbrechen.", "La confiance s’applique à cet utilisateur Windows et autorise le relais local à traiter le trafic chatgpt.com. Arrêtez le service et fermez Codex avant renouvellement ou suppression. L’arrêt peut interrompre les connexions actives.", "信任适用于此 Windows 用户，允许本地中继处理 chatgpt.com 流量。更新或移除前请停止服务并关闭 Codex。停止可能中断活动连接。", "信任適用於此 Windows 使用者，允許本機中繼處理 chatgpt.com 流量。更新或移除前請停止服務並關閉 Codex。停止可能中斷使用中的連線。", "Доверие действует для этого пользователя Windows и позволяет локальному ретранслятору обрабатывать трафик chatgpt.com. Перед обновлением или удалением остановите службу и закройте Codex. Остановка может прервать соединения.", "信頼はこの Windows ユーザーに適用され、ローカルリレーが chatgpt.com の通信を処理します。更新・解除前にサービスを停止し Codex を閉じてください。停止すると接続が中断される場合があります。", "Güven bu Windows kullanıcısı için geçerlidir ve yerel aktarıcının chatgpt.com trafiğini işlemesine izin verir. Yenilemeden veya kaldırmadan önce hizmeti durdurup Codex’i kapatın. Durdurma etkin bağlantıları kesebilir.", "Tin cậy áp dụng cho người dùng Windows này, cho phép bộ chuyển tiếp cục bộ xử lý lưu lượng chatgpt.com. Dừng dịch vụ và đóng Codex trước khi gia hạn hoặc gỡ. Dừng có thể ngắt kết nối đang dùng."],
  trialRisk: ["For up to 3 minutes, two UI flags are adjusted for the whole signed-in account, across models. Usage, credits and server limits remain unchanged. Observed exhaustion is required; a response does not prove the composer recovered.", "최대 3분 동안 모델 구분 없이 로그인 계정 전체의 UI 표시 두 항목을 교정합니다. 사용량·크레딧·서버 한도는 유지됩니다. 실제 소진 관찰이 필요하며, 응답 생성만으로 입력창 복구가 입증되지는 않습니다.", "Bis zu 3 Minuten werden zwei UI-Werte für das gesamte angemeldete Konto modellübergreifend angepasst. Nutzung, Guthaben und Serverlimits bleiben unverändert. Eine beobachtete Erschöpfung ist erforderlich; eine Antwort beweist keine Wiederherstellung der Eingabe.", "Pendant 3 minutes au maximum, deux indicateurs d’interface sont ajustés pour tout le compte connecté, tous modèles confondus. Usage, crédits et limites serveur restent inchangés. Un épuisement observé est requis ; une réponse ne prouve pas le rétablissement de la saisie.", "最多 3 分钟内，调整整个已登录账户的两个界面标志，影响所有模型。用量、余额和服务器限制不变。需要观察到额度耗尽；收到响应不代表输入框已恢复。", "最多 3 分鐘內，調整整個已登入帳戶的兩個介面旗標，影響所有模型。用量、點數和伺服器限制不變。必須觀察到額度耗盡；收到回應不代表輸入框已恢復。", "Не более 3 минут корректируются два флага интерфейса всего аккаунта для всех моделей. Использование, кредиты и лимиты сервера не меняются. Требуется наблюдаемое исчерпание; ответ не доказывает восстановление ввода.", "最大3分間、ログイン中のアカウント全体でモデルを区別せず2つのUIフラグを補正します。使用量・クレジット・サーバー制限は変更しません。上限到達の観察が必要で、応答だけでは入力欄の復旧を証明できません。", "En fazla 3 dakika boyunca tüm modellerde oturum açmış hesabın iki arayüz bayrağı düzeltilir. Kullanım, krediler ve sunucu sınırları değişmez. Kotanın tükendiğinin gözlenmesi gerekir; yanıt, giriş alanının düzeldiğini kanıtlamaz.", "Trong tối đa 3 phút, điều chỉnh hai cờ giao diện của toàn bộ tài khoản đã đăng nhập, cho mọi mô hình. Mức dùng, tín dụng và giới hạn máy chủ không đổi. Cần quan sát thấy hết hạn mức; phản hồi không chứng minh ô nhập đã phục hồi."],
  error: ["Completion could not be confirmed. Refresh status before retrying.", "완료 여부를 확인하지 못했습니다. 재시도 전에 상태를 새로고침하세요.", "Abschluss nicht bestätigt. Vor einem erneuten Versuch Status aktualisieren.", "Fin non confirmée. Actualisez l’état avant de réessayer.", "无法确认是否完成。重试前请刷新状态。", "無法確認是否完成。重試前請重新整理狀態。", "Завершение не подтверждено. Обновите состояние перед повтором.", "完了を確認できませんでした。再試行前に状態を更新してください。", "Tamamlandığı doğrulanamadı. Yeniden denemeden önce durumu yenileyin.", "Chưa xác nhận hoàn tất. Làm mới trạng thái trước khi thử lại."],
  done: ["Action confirmed. Status refreshed.", "동작을 확인하고 상태를 새로고침했습니다.", "Aktion bestätigt. Status aktualisiert.", "Action confirmée. État actualisé.", "操作已确认，状态已刷新。", "操作已確認，狀態已重新整理。", "Действие подтверждено. Состояние обновлено.", "操作を確認し、状態を更新しました。", "İşlem doğrulandı. Durum yenilendi.", "Đã xác nhận thao tác và làm mới trạng thái."],
  certificate: ["Certificate", "인증서", "Zertifikat", "Certificat", "证书", "憑證", "Сертификат", "証明書", "Sertifika", "Chứng chỉ"],
  runtime: ["Service", "서비스", "Dienst", "Service", "服务", "服務", "Служба", "サービス", "Hizmet", "Dịch vụ"],
  expiry: ["Expires", "만료", "Ablauf", "Expiration", "到期", "到期", "Истекает", "有効期限", "Bitiş", "Hết hạn"],
  renewalDue: ["Certificate renewal is due soon.", "인증서 갱신 시기가 다가옵니다.", "Zertifikat bald erneuern.", "Le certificat doit bientôt être renouvelé.", "证书即将需要更新。", "憑證即將需要更新。", "Скоро потребуется обновить сертификат.", "証明書の更新時期が近づいています。", "Sertifika yakında yenilenmeli.", "Chứng chỉ sắp cần gia hạn."],
  unsupported: ["Available on supported Windows installations only.", "지원되는 Windows 설치에서만 사용할 수 있습니다.", "Nur für unterstützte Windows-Installationen.", "Disponible uniquement sur les installations Windows prises en charge.", "仅适用于受支持的 Windows 安装。", "僅適用於受支援的 Windows 安裝。", "Доступно только для поддерживаемых установок Windows.", "対応する Windows 環境でのみ利用できます。", "Yalnızca desteklenen Windows kurulumlarında kullanılabilir.", "Chỉ dùng được trên bản cài Windows được hỗ trợ."],
  localOnly: ["Changes require this computer’s local dashboard. Save drafts and close Codex before launching it here.", "변경은 이 컴퓨터의 로컬 대시보드에서 가능합니다. 여기서 앱을 실행하기 전에 초안을 저장하고 Codex를 닫으세요.", "Änderungen erfordern das lokale Dashboard dieses Computers. Vor dem Start Entwürfe speichern und Codex schließen.", "Les modifications nécessitent le tableau de bord local de cet ordinateur. Enregistrez les brouillons et fermez Codex avant de le lancer ici.", "更改需要此计算机的本地仪表板。在此启动前，请保存草稿并关闭 Codex。", "變更需要此電腦的本機儀表板。在此啟動前，請儲存草稿並關閉 Codex。", "Изменения требуют локальной панели этого компьютера. Сохраните черновики и закройте Codex перед запуском здесь.", "変更にはこのPCのローカルダッシュボードが必要です。ここから起動する前に下書きを保存し Codex を閉じてください。", "Değişiklikler bu bilgisayarın yerel panosunu gerektirir. Buradan açmadan önce taslakları kaydedip Codex’i kapatın.", "Thay đổi cần bảng điều khiển cục bộ của máy này. Lưu bản nháp và đóng Codex trước khi mở tại đây."],
} as const satisfies Record<string, Row>;

export function desktopCompatibilityCopy(locale: Locale): Record<`desktopCompat.${keyof typeof rows}`, string> {
  const index = locales.indexOf(locale);
  return Object.fromEntries(Object.entries(rows).map(([key, values]) => [`desktopCompat.${key}`, values[index]!])) as Record<`desktopCompat.${keyof typeof rows}`, string>;
}
