import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { deriveJawcodeAliases } from "../src/providers/derive";

const PROVIDER_ALIASES = deriveJawcodeAliases();

type RawModel = {
  id?: string;
  contextWindow?: number;
  maxTokens?: number;
  input?: ("text" | "image")[];
  reasoning?: boolean;
  wireModelId?: string;
  cost?: {
    input: number;
    output: number;
    cacheRead: number;
    cacheWrite: number;
  };
};

const sourcePath = process.env.JAWCODE_MODELS_JSON
  ? resolve(process.env.JAWCODE_MODELS_JSON)
  : resolve(process.cwd(), "../jawcode/packages/ai/src/models.json");
const outPath = resolve(process.cwd(), "src/generated/jawcode-model-metadata.ts");
const CONTEXT_WINDOW_OVERRIDES: Record<string, number> = {
  "anthropic/claude-sonnet-4-6": 200_000,
  "anthropic/claude-sonnet-4-6[1m]": 200_000,
};

if (!existsSync(sourcePath)) {
  throw new Error(`jawcode models.json not found: ${sourcePath}`);
}

const registry = JSON.parse(readFileSync(sourcePath, "utf-8")) as Record<string, Record<string, RawModel>>;
// Vendor bundles whose model-level list prices are used for cross-provider fallback
// (policy: a model follows its official vendor price regardless of which provider
// serves it — e.g. kiro/claude-opus-4-6 -> anthropic price). Priority order matters:
// first nonzero exact modelId match wins, so canonical vendors come first.
const COST_VENDOR_BUNDLES = [
  "anthropic", "openai", "google", "moonshot", "minimax", "deepseek", "xai",
  "zai", "mistral", "cerebras", "azure-openai", "amazon-bedrock", "xiaomi",
];

const allowedProviders = Array.from(
  new Set([...Object.values(PROVIDER_ALIASES), ...COST_VENDOR_BUNDLES]),
).sort();
const lines: string[] = [];

function compactRow(values: unknown[]): unknown[] {
  while (values.length > 0 && values[values.length - 1] === undefined) values.pop();
  return values;
}

lines.push("/* eslint-disable */");
lines.push("// Generated by scripts/generate-jawcode-metadata.ts. Do not edit by hand.");
lines.push("");
lines.push("export interface JawcodeModelMetadata {");
lines.push("  provider: string;");
lines.push("  id: string;");
lines.push("  contextWindow?: number;");
lines.push("  maxTokens?: number;");
lines.push("  input?: (\"text\" | \"image\")[];");
lines.push("  reasoning?: boolean;");
lines.push("  wireModelId?: string;");
lines.push("  cost?: { input: number; output: number; cacheRead: number; cacheWrite: number };");
lines.push("}");
lines.push("");
lines.push("const PROVIDER_ALIASES: Record<string, string> = " + JSON.stringify(PROVIDER_ALIASES, null, 2) + " as const;");
lines.push("");
lines.push("type Row = readonly [id: string, contextWindow?: number | null, maxTokens?: number | null, input?: string | null, reasoning?: 0 | 1 | null, wireModelId?: string | null, costInput?: number | null, costOutput?: number | null, costCacheRead?: number | null, costCacheWrite?: number | null];");
lines.push("const DATA: Record<string, readonly Row[]> = {");

for (const provider of allowedProviders) {
  const models = registry[provider] ?? {};
  const rows = Object.entries(models)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, model]) => compactRow([
      id,
      CONTEXT_WINDOW_OVERRIDES[`${provider}/${id}`] ?? model.contextWindow,
      model.maxTokens,
      Array.isArray(model.input) ? model.input.join(",") : undefined,
      model.reasoning === undefined ? undefined : (model.reasoning ? 1 : 0),
      model.wireModelId,
      model.cost?.input,
      model.cost?.output,
      model.cost?.cacheRead,
      model.cost?.cacheWrite,
    ]));
  lines.push(`  ${JSON.stringify(provider)}: ${JSON.stringify(rows)},`);
}

lines.push("};");
lines.push("");
lines.push("export function resolveJawcodeProvider(provider: string): string | undefined {");
lines.push("  return PROVIDER_ALIASES[provider];");
lines.push("}");
lines.push("");
lines.push("export function getJawcodeModelMetadata(provider: string, modelId: string): JawcodeModelMetadata | undefined {");
lines.push("  const row = DATA[provider]?.find(r => r[0] === modelId);");
lines.push("  if (!row) return undefined;");
lines.push("  return rowToMetadata(provider, row);");
lines.push("}");
lines.push("");
lines.push("export function getJawcodeModelMetadataCaseInsensitive(provider: string, modelId: string): JawcodeModelMetadata | undefined {");
lines.push("  const lower = modelId.toLowerCase();");
lines.push("  const row = DATA[provider]?.find(r => r[0].toLowerCase() === lower);");
lines.push("  if (!row) return undefined;");
lines.push("  return rowToMetadata(provider, row);");
lines.push("}");
lines.push("");
lines.push("export function listJawcodeModelMetadata(provider: string): JawcodeModelMetadata[] {");
lines.push("  return (DATA[provider] ?? []).map(row => rowToMetadata(provider, row));");
lines.push("}");
lines.push("");
lines.push("// Cross-provider model-level price fallback (260720 WP5): a model follows its");
lines.push("// official vendor price regardless of the serving provider. Exact modelId match in");
lines.push("// priority-ordered vendor bundles; first nonzero cost wins.");
lines.push("const COST_VENDOR_PRIORITY = " + JSON.stringify(COST_VENDOR_BUNDLES) + ";");
lines.push("export function findJawcodeCostByModelId(modelId: string): { provider: string; cost: { input: number; output: number; cacheRead: number; cacheWrite: number } } | undefined {");
lines.push("  for (const provider of COST_VENDOR_PRIORITY) {");
lines.push("    const row = DATA[provider]?.find(r => r[0] === modelId);");
lines.push("    if (!row) continue;");
lines.push("    const meta = rowToMetadata(provider, row);");
lines.push("    if (meta.cost && (meta.cost.input !== 0 || meta.cost.output !== 0 || meta.cost.cacheRead !== 0 || meta.cost.cacheWrite !== 0)) {");
lines.push("      return { provider, cost: meta.cost };");
lines.push("    }");
lines.push("  }");
lines.push("  return undefined;");
lines.push("}");
lines.push("");
lines.push("function rowToMetadata(provider: string, row: Row): JawcodeModelMetadata {");
lines.push("  const [id, contextWindow, maxTokens, input, reasoning, wireModelId, costInput, costOutput, costCacheRead, costCacheWrite] = row;");
lines.push("  const hasCost = costInput != null && costOutput != null && costCacheRead != null && costCacheWrite != null;");
lines.push("  return {");
lines.push("    provider, id,");
lines.push("    ...(contextWindow != null ? { contextWindow } : {}),");
lines.push("    ...(maxTokens != null ? { maxTokens } : {}),");
lines.push("    ...(input ? { input: input.split(\",\") as (\"text\" | \"image\")[] } : {}),");
lines.push("    ...(reasoning != null ? { reasoning: reasoning === 1 } : {}),");
lines.push("    ...(wireModelId != null ? { wireModelId } : {}),");
lines.push("    ...(hasCost ? { cost: { input: costInput, output: costOutput, cacheRead: costCacheRead, cacheWrite: costCacheWrite } } : {}),");
lines.push("  };");
lines.push("}");
lines.push("");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join("\n"));
console.log(`wrote ${outPath} from ${sourcePath}`);
