use anyhow::Result;
use axum::{
    Router,
    body::Body,
    extract::{
        FromRequestParts, State, WebSocketUpgrade,
        ws::{Message, WebSocket},
    },
    http::{HeaderMap, HeaderName, HeaderValue, Request, Response, StatusCode, Uri},
    response::IntoResponse,
    routing::any,
};
use futures_util::{SinkExt, StreamExt};
use reqwest::Client;
use tokio::net::TcpListener;
use tokio_tungstenite::{connect_async, tungstenite::client::IntoClientRequest};
use tokio_util::sync::CancellationToken;

use crate::{
    assertion::{ASSERTION_HEADER, AssertionVerifier},
    config::AgentConfig,
};

const REQUEST_DENY: &[&str] = &[
    "connection",
    "cookie",
    "host",
    "proxy-authenticate",
    "proxy-authorization",
    "upgrade",
    "x-forwarded-for",
    "x-forwarded-host",
    "x-forwarded-proto",
    "x-real-ip",
    "x-opencodex-api-key",
    "x-opencodex-remote-token",
    "x-ocxr-target-path",
];
const RESPONSE_DENY: &[&str] = &[
    "connection",
    "set-cookie",
    "set-cookie2",
    "proxy-authenticate",
    "proxy-authorization",
];

#[derive(Clone)]
struct AppState {
    verifier: AssertionVerifier,
    client: Client,
    opencodex_url: String,
}

fn denied(name: &HeaderName, response: bool) -> bool {
    let lower = name.as_str();
    lower.starts_with("cf-")
        || lower.starts_with("x-ocxr-")
        // Each relay hop owns its WebSocket handshake. Forwarding the client's
        // generated key/version headers would duplicate those generated by the
        // upstream WebSocket client and can make an otherwise valid upgrade fail.
        || (!response && lower.starts_with("sec-websocket-"))
        || (response && RESPONSE_DENY.contains(&lower))
        || (!response && (REQUEST_DENY.contains(&lower) || lower == ASSERTION_HEADER))
}

fn target_uri(base: &str, uri: &Uri) -> Result<String> {
    Ok(format!(
        "{}{}",
        base.trim_end_matches('/'),
        uri.path_and_query()
            .map(|value| value.as_str())
            .unwrap_or("/")
    ))
}

fn sanitized_request_headers(input: &HeaderMap) -> HeaderMap {
    let mut output = HeaderMap::new();
    for (name, value) in input {
        if denied(name, false) {
            continue;
        }
        if name == axum::http::header::AUTHORIZATION
            && value
                .to_str()
                .ok()
                .and_then(|value| value.strip_prefix("Bearer "))
                .is_some_and(|token| token.starts_with("ocxr_"))
        {
            continue;
        }
        output.append(name, value.clone());
    }
    output.insert(
        axum::http::header::HOST,
        HeaderValue::from_static("127.0.0.1:10100"),
    );
    output.insert(
        axum::http::header::ORIGIN,
        HeaderValue::from_static("http://127.0.0.1:10100"),
    );
    output
}

async fn proxy(State(state): State<AppState>, req: Request<Body>) -> impl IntoResponse {
    if let Err(error) = state
        .verifier
        .verify(req.method(), req.uri(), req.headers())
        .await
    {
        tracing::warn!(reason=%error, "request assertion rejected");
        return StatusCode::NOT_FOUND.into_response();
    }
    let (mut parts, body) = req.into_parts();
    if parts.headers.get(axum::http::header::UPGRADE).is_some() {
        return match WebSocketUpgrade::from_request_parts(&mut parts, &state).await {
            Ok(upgrade) => upgrade
                .on_upgrade(move |socket| relay_websocket(socket, state, parts.uri, parts.headers))
                .into_response(),
            Err(_) => StatusCode::BAD_REQUEST.into_response(),
        };
    }
    let target = match target_uri(&state.opencodex_url, &parts.uri) {
        Ok(target) => target,
        Err(_) => return StatusCode::BAD_REQUEST.into_response(),
    };
    let headers = sanitized_request_headers(&parts.headers);
    let request = state
        .client
        .request(parts.method, target)
        .headers(headers)
        .body(reqwest::Body::wrap_stream(body.into_data_stream()));
    let upstream = match request.send().await {
        Ok(response) => response,
        Err(error) => {
            tracing::warn!(%error, "OpenCodex upstream request failed");
            return StatusCode::BAD_GATEWAY.into_response();
        }
    };
    let mut response = Response::builder().status(upstream.status());
    for (name, value) in upstream.headers() {
        if !denied(name, true) {
            response = response.header(name, value);
        }
    }
    match response.body(Body::from_stream(upstream.bytes_stream())) {
        Ok(response) => response.into_response(),
        Err(_) => StatusCode::BAD_GATEWAY.into_response(),
    }
}

async fn relay_websocket(
    client: WebSocket,
    state: AppState,
    uri: Uri,
    incoming_headers: HeaderMap,
) {
    let target = match target_uri(&state.opencodex_url, &uri) {
        Ok(target) => target
            .replacen("http://", "ws://", 1)
            .replacen("https://", "wss://", 1),
        Err(_) => return,
    };
    let mut request = match target.into_client_request() {
        Ok(request) => request,
        Err(_) => return,
    };
    for (name, value) in sanitized_request_headers(&incoming_headers) {
        if let Some(name) = name {
            request.headers_mut().append(name, value);
        }
    }
    let (upstream, _) = match connect_async(request).await {
        Ok(value) => value,
        Err(error) => {
            tracing::warn!(%error, "OpenCodex websocket connect failed");
            return;
        }
    };
    let (mut client_tx, mut client_rx) = client.split();
    let (mut upstream_tx, mut upstream_rx) = upstream.split();
    let to_upstream = async {
        while let Some(Ok(message)) = client_rx.next().await {
            let converted = match message {
                Message::Text(value) => {
                    tokio_tungstenite::tungstenite::Message::Text(value.to_string().into())
                }
                Message::Binary(value) => tokio_tungstenite::tungstenite::Message::Binary(value),
                Message::Ping(value) => tokio_tungstenite::tungstenite::Message::Ping(value),
                Message::Pong(value) => tokio_tungstenite::tungstenite::Message::Pong(value),
                Message::Close(_) => tokio_tungstenite::tungstenite::Message::Close(None),
            };
            if upstream_tx.send(converted).await.is_err() {
                break;
            }
        }
    };
    let to_client = async {
        while let Some(Ok(message)) = upstream_rx.next().await {
            let converted = match message {
                tokio_tungstenite::tungstenite::Message::Text(value) => {
                    Message::Text(value.to_string().into())
                }
                tokio_tungstenite::tungstenite::Message::Binary(value) => Message::Binary(value),
                tokio_tungstenite::tungstenite::Message::Ping(value) => Message::Ping(value),
                tokio_tungstenite::tungstenite::Message::Pong(value) => Message::Pong(value),
                tokio_tungstenite::tungstenite::Message::Close(_) => Message::Close(None),
                tokio_tungstenite::tungstenite::Message::Frame(_) => continue,
            };
            if client_tx.send(converted).await.is_err() {
                break;
            }
        }
    };
    tokio::select! { _ = to_upstream => {}, _ = to_client => {} }
}

pub async fn serve(config: AgentConfig, shutdown: CancellationToken) -> Result<()> {
    let state = AppState {
        verifier: AssertionVerifier::new(&config)?,
        client: Client::builder().build()?,
        opencodex_url: config.opencodex_url.clone(),
    };
    let app = Router::new().fallback(any(proxy)).with_state(state);
    let listener = TcpListener::bind(&config.ingress).await?;
    tracing::info!(bind=%config.ingress, "local ingress ready");
    axum::serve(listener, app)
        .with_graceful_shutdown(shutdown.cancelled_owned())
        .await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn websocket_handshake_headers_are_regenerated_per_hop() {
        let mut input = HeaderMap::new();
        input.insert("upgrade", HeaderValue::from_static("websocket"));
        input.insert("sec-websocket-key", HeaderValue::from_static("client-key"));
        input.insert("sec-websocket-version", HeaderValue::from_static("13"));
        input.insert("x-client-feature", HeaderValue::from_static("preserved"));

        let output = sanitized_request_headers(&input);
        assert!(!output.contains_key("upgrade"));
        assert!(!output.contains_key("sec-websocket-key"));
        assert!(!output.contains_key("sec-websocket-version"));
        assert_eq!(
            output.get("x-client-feature"),
            Some(&HeaderValue::from_static("preserved"))
        );
    }
}
